// <auto-generated />
using System;
using ClothesStore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClothesStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210516185919_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClothesStore.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Clothes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ClothesTypeDestinantion")
                        .HasColumnType("int");

                    b.Property<string>("ClothesTypeName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float>("PromoutionPercent")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ClothesTypeDestinantion", "ClothesTypeName");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.ClothesMark", b =>
                {
                    b.Property<int>("ClothesId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CountInStock")
                        .HasColumnType("int");

                    b.HasKey("ClothesId", "SizeId");

                    b.HasIndex("SizeId");

                    b.ToTable("ClothesMarks");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.ClothesOrder", b =>
                {
                    b.Property<int>("ClothesUnitId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ClothesUnitClothesId")
                        .HasColumnType("int");

                    b.Property<int>("ClothesUnitSizeId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPerSingle")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("ClothesUnitId", "OrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ClothesUnitClothesId", "ClothesUnitSizeId");

                    b.ToTable("ClothesOrders");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.ClothesType", b =>
                {
                    b.Property<int>("Destinantion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("imgSrc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Destinantion", "Name");

                    b.ToTable("ClothesTypes");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Canceled")
                        .HasColumnType("bit");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("PayMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Clothes", b =>
                {
                    b.HasOne("ClothesStore.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("ClothesStore.Domain.Entities.ClothesType", "ClothesType")
                        .WithMany("Clothes")
                        .HasForeignKey("ClothesTypeDestinantion", "ClothesTypeName");

                    b.Navigation("Brand");

                    b.Navigation("ClothesType");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.ClothesMark", b =>
                {
                    b.HasOne("ClothesStore.Domain.Entities.Clothes", "Clothes")
                        .WithMany("ClothesMarksInStock")
                        .HasForeignKey("ClothesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesStore.Domain.Entities.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothes");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.ClothesOrder", b =>
                {
                    b.HasOne("ClothesStore.Domain.Entities.Order", "Order")
                        .WithMany("ClothesOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesStore.Domain.Entities.ClothesMark", "ClothesUnit")
                        .WithMany()
                        .HasForeignKey("ClothesUnitClothesId", "ClothesUnitSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClothesUnit");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Order", b =>
                {
                    b.HasOne("ClothesStore.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("ClothesStore.Domain.Entities.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.OwnsOne("ClothesStore.Domain.Entities.Address", "ShipAddress", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShipAddress")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Client");

                    b.Navigation("Manager");

                    b.Navigation("ShipAddress");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Clothes", b =>
                {
                    b.Navigation("ClothesMarksInStock");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.ClothesType", b =>
                {
                    b.Navigation("Clothes");
                });

            modelBuilder.Entity("ClothesStore.Domain.Entities.Order", b =>
                {
                    b.Navigation("ClothesOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
